name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        java: [ '19.0.2' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Delete Old Artifacts
      uses: actions/github-script@v6
      id: artifact
      with:
        script: |
          const res = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })

          res.data.artifacts
            .forEach(({ id }) => {
              github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: id,
              })
            })      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: ${{ matrix.java }}
    - name: Echo JAVA_HOME
      run: echo $JAVA_HOME
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Execute build
      run: ./gradlew --info --stacktrace build
    - name: Execute runtime
      run: ./gradlew --info --stacktrace runtime
    - name: Execute jpackage
      run: ./gradlew --info --stacktrace jpackage
    - name: Upload DMG as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: chess-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
        path: build/jpackage/*.dmg
        if-no-files-found: ignore
    - name: Upload EXE as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: chess-jdk${{ matrix.java }}-${{ matrix.os }}-exe
        path: build/jpackage/*.exe
        if-no-files-found: ignore
    - name: Upload MSI as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: chess-jdk${{ matrix.java }}-${{ matrix.os }}-msi
        path: build/jpackage/*.msi
        if-no-files-found: ignore
    - name: Upload DEB as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: chess-jdk${{ matrix.java }}-${{ matrix.os }}-deb
        path: build/jpackage/*.deb
        if-no-files-found: ignore
    - name: Upload RPM as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: chess-jdk${{ matrix.java }}-${{ matrix.os }}-rpm
        path: build/jpackage/*.rpm
        if-no-files-found: ignore
